FROM golang:1.11 as builder
ENV PKG_NAME=github.com/intel/multus-cni
ENV PKG_PATH=$GOPATH/src/$PKG_NAME
WORKDIR $PKG_PATH
COPY . $PKG_PATH/
WORKDIR $PKG_PATH/webhook/server
RUN go install
WORKDIR $PKG_PATH/webhook/deployment
RUN go install

FROM golang:1.11
RUN mkdir /webhook
COPY --from=builder /go/bin/* /webhook/
WORKDIR /webhook
CMD ["./server"]
