//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GpuSharing) DeepCopyInto(out *GpuSharing) {
	*out = *in
	if in.TimeSlicingConfig != nil {
		in, out := &in.TimeSlicingConfig, &out.TimeSlicingConfig
		*out = new(TimeSlicingConfig)
		**out = **in
	}
	if in.SpacePartitioningConfig != nil {
		in, out := &in.SpacePartitioningConfig, &out.SpacePartitioningConfig
		*out = new(SpacePartitioningConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GpuSharing.
func (in *GpuSharing) DeepCopy() *GpuSharing {
	if in == nil {
		return nil
	}
	out := new(GpuSharing)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetConfig) DeepCopyInto(out *NetConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetConfig.
func (in *NetConfig) DeepCopy() *NetConfig {
	if in == nil {
		return nil
	}
	out := new(NetConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpacePartitioningConfig) DeepCopyInto(out *SpacePartitioningConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpacePartitioningConfig.
func (in *SpacePartitioningConfig) DeepCopy() *SpacePartitioningConfig {
	if in == nil {
		return nil
	}
	out := new(SpacePartitioningConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeSlicingConfig) DeepCopyInto(out *TimeSlicingConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeSlicingConfig.
func (in *TimeSlicingConfig) DeepCopy() *TimeSlicingConfig {
	if in == nil {
		return nil
	}
	out := new(TimeSlicingConfig)
	in.DeepCopyInto(out)
	return out
}
