---
{{- if eq .Values.pluginType "thin" }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: multus-cni
  namespace: {{ include "multusCni.namespace" . }}
  labels:
    {{- include "multusCni.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "multusCni.selectorLabels" . | nindent 6 }}
  updateStrategy:
    {{- toYaml .Values.updateStrategy | nindent 4 }}
  template:
    metadata:
      labels:
        {{- include "multusCni.labels" . | nindent 8 }}
    spec:
      hostNetwork: true
      serviceAccountName: {{ .Values.serviceAccount.name }}
  {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
  {{- end }}
  {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
  {{- end }}
      containers:
        - name: multus-cni
          image: {{ include "multusCni.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - {{ quote .Values.thin.container.command }}
  {{- if .Values.thin.container.args }}
          args:
    {{- range .Values.thin.container.args }}
            - {{ quote (tpl . $) }}
    {{- end }}
  {{- end }}
  {{- with .Values.additionalEnv }}
          env:
            {{- toYaml . | nindent 12 }}
  {{- end }}
          resources:
            {{- toYaml .Values.thin.container.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          terminationMessagePolicy: FallbackToLogsOnError
          volumeMounts:
            - name: cni-config
              mountPath: {{ .Values.cniConfig.mountPath }}
            - name: cni-bin
              mountPath: {{ .Values.cniBin.mountPath }}
  {{- with .Values.additionalVolumeMounts }} 
            {{- toYaml . | nindent 12 }}
  {{- end }}
      initContainers:
        - name: install-multus-cni-binary
          image: {{ include "multusCni.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - {{ quote .Values.thin.initContainer.command }}
  {{- if .Values.thin.initContainer.args }}
          args:
    {{- range .Values.thin.initContainer.args }}
            - {{ quote (tpl . $) }}
    {{- end }}
  {{- end }}
          resources:
            {{- toYaml .Values.thin.initContainer.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          terminationMessagePolicy: FallbackToLogsOnError
          volumeMounts:
            - name: cni-bin
              mountPath: {{ .Values.cniBin.mountPath }}
              mountPropagation: Bidirectional
      volumes:
        - name: cni-config
          hostPath:
            path: {{ .Values.cniConfig.hostPath }}
        - name: cni-bin
          hostPath:
            path: {{ .Values.cniBin.hostPath }}
  {{- with .Values.additionalVolumes }} 
        {{- toYaml . | nindent 8 }}
  {{- end }}
      terminationGracePeriodSeconds: 10
{{- end }}
