apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-nad
spec: 
  config: '{
    "cniVersion": "0.3.1",
    "name": "testnet",
    "type": "bridge",
    "bridge": "testnet0",
    "ipam": {
        "type": "host-local",
        "subnet": "10.10.0.0/16"
    }
}'
