#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
# SPDX-License-Identifier: Apache-2.0
#
# Adapted from ovn-kubernetes contrib/perf for Multus CI reporting.

"""
Post performance reports as comments to GitHub PRs.

Supports:
- Multiple PRs
- Multiple workload reports
- Automatic chunking for large comments (GitHub 65k limit)
- Collapsible sections per workload
- Updates existing comments instead of creating new ones
- Collapses the immediately prior run under a "Previous Run" section

Usage:
    python post-pr-comment.py --pr 123 --reports-dir ./reports --run-id 456 --status success
"""

import argparse
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

import requests
from github_common import get_github_token, get_repo_info


MAX_COMMENT_SIZE = 60000  # GitHub limit is 65536
PREVIOUS_RUN_SEPARATOR = "\n---\n\n### Previous Run\n\n"
LEGACY_PREVIOUS_RUNS_SEPARATOR = "\n---\n\n### Previous Runs\n\n"
COMMENT_FOOTER = "\n---\n🤖 Generated by performance-report workflow"
PREVIOUS_RUN_TIMESTAMP_FORMAT = '%Y-%m-%d %H:%M:%S UTC'
MULTIPART_COMMENT_PATTERN = re.compile(r'\(Part\s*\d+/\d+\)')
DETAILS_OPEN_PATTERN = re.compile(r'<details\b')
DETAILS_CLOSE_PATTERN = re.compile(r'</details>')


def find_reports(reports_dir: Path) -> list[dict[str, str]]:
    """
    Find all performance report markdown files in the reports directory.

    Returns:
        List of dicts with 'workload' and 'content' keys
    """
    reports = []

    if not reports_dir.exists():
        return reports

    for workload_dir in reports_dir.iterdir():
        if not workload_dir.is_dir():
            continue

        # Look for performance_report.md in the workload directory
        report_file = workload_dir / 'performance_report.md'

        if report_file.exists():
            content = report_file.read_text()
            reports.append({
                'workload': workload_dir.name,
                'content': content
            })
            print(f"Found report for workload: {workload_dir.name}", file=sys.stderr)

    return reports


def build_header(run_id: str, run_url: str, status: str, baseline_id: str = None,
                baseline_url: str = None, part_num: int = None, total_parts: int = None) -> str:
    """Build the comment header."""
    header = "## 🚀 Performance Test Results"

    if part_num is not None and total_parts is not None:
        header += f" (Part {part_num}/{total_parts})"

    header += "\n\n"
    header += f"**Status:** {'✅ Completed' if status == 'success' else '❌ Failed'}\n"
    header += f"**Workflow Run:** [#{run_id}]({run_url})\n"

    if baseline_id and baseline_url:
        header += f"**Baseline:** [Run #{baseline_id}]({baseline_url})\n"

    header += "\n---\n\n"

    return header


def create_comment_chunks(reports: list[dict], run_id: str, run_url: str, status: str,
                         baseline_id: str = None, baseline_url: str = None) -> list[str]:
    """
    Create comment chunks, splitting if necessary to fit GitHub's size limit.

    Returns:
        List of comment bodies ready to post
    """
    footer = COMMENT_FOOTER

    if not reports:
        # Generate a basic report if no detailed reports exist
        basic_report = build_header(run_id, run_url, status, baseline_id, baseline_url)

        if status == 'success':
            basic_report += "### Results Summary\n"
            basic_report += "Performance test completed successfully.\n\n"
            basic_report += "**Artifacts Available:**\n"
            basic_report += "- Performance metrics data\n"
            basic_report += "- Cluster logs\n"
        else:
            basic_report += "### ⚠️ Test Failed\n"
            basic_report += f"The performance test failed to complete. Please check the [workflow logs]({run_url}) for details.\n"

        basic_report += footer
        return [basic_report]

    # Build individual workload sections as collapsible details
    workload_sections = []
    for report in reports:
        section = f"<details>\n<summary><strong>{report['workload']}</strong></summary>\n\n"
        section += report['content']
        section += "\n</details>\n\n"
        workload_sections.append(section)

    # Try to fit all in one comment first
    single_comment = build_header(run_id, run_url, status, baseline_id, baseline_url)
    single_comment += f"**Workloads Tested:** {len(reports)}\n\n---\n\n"
    single_comment += ''.join(workload_sections)
    single_comment += footer

    if len(single_comment) <= MAX_COMMENT_SIZE:
        return [single_comment]

    # Need to chunk - split workloads across multiple comments
    print(f"Comment too large ({len(single_comment)} chars), chunking...", file=sys.stderr)

    chunks = []
    current_chunk = ''
    current_workloads = []

    for i, section in enumerate(workload_sections):
        test_chunk = current_chunk + section

        # Estimate with header and footer (conservative)
        estimated_size = len(test_chunk) + 500

        if estimated_size > MAX_COMMENT_SIZE and current_chunk:
            # Current chunk is full, save it and start new one
            chunks.append({
                'content': current_chunk,
                'workloads': current_workloads.copy()
            })
            current_chunk = section
            current_workloads = [reports[i]['workload']]
        else:
            current_chunk = test_chunk
            current_workloads.append(reports[i]['workload'])

    # Add the last chunk
    if current_chunk:
        chunks.append({
            'content': current_chunk,
            'workloads': current_workloads
        })

    # Build final comments with part numbers
    total_parts = len(chunks)
    comments = []

    for idx, chunk in enumerate(chunks):
        part_num = idx + 1
        comment = build_header(run_id, run_url, status, baseline_id, baseline_url, part_num, total_parts)
        comment += f"**Workloads in this part:** {', '.join(chunk['workloads'])}\n\n"
        comment += "---\n\n"
        comment += chunk['content']
        comment += footer
        comments.append(comment)

    return comments


def _next_page_url(link_header: str | None) -> str | None:
    """Return the next page URL from a GitHub Link response header, if any."""
    if not link_header:
        return None
    for link in requests.utils.parse_header_links(link_header):
        if link.get('rel') == 'next':
            return link.get('url')
    return None


def _acting_bot_login() -> str:
    """Login used when this workflow posts comments (GITHUB_TOKEN → github-actions[bot])."""
    return os.getenv('GITHUB_BOT_LOGIN', 'github-actions[bot]')


def find_existing_comment(owner: str, repo: str, pr_number: int, token: str) -> dict | None:
    """Find the most recent performance test results comment on the PR."""
    url = f"https://api.github.com/repos/{owner}/{repo}/issues/{pr_number}/comments"
    headers = {
        'Authorization': f'token {token}',
        'Accept': 'application/vnd.github.v3+json'
    }
    params = {'per_page': 100}
    all_comments: list[dict] = []

    while url:
        response = requests.get(url, headers=headers, params=params, timeout=30)
        # Next-page URLs already include query parameters.
        params = None

        if response.status_code != 200:
            print(f"Failed to fetch comments: {response.status_code}", file=sys.stderr)
            return None

        page = response.json()
        if isinstance(page, list):
            all_comments.extend(page)

        url = _next_page_url(response.headers.get('Link'))

    bot_login = _acting_bot_login()

    # Find comments that look like performance test results (reverse order to get most recent first)
    for comment in reversed(all_comments):
        author = (comment.get('user') or {}).get('login')
        if author != bot_login:
            continue
        body = comment.get('body', '')
        if ('## 🚀 Performance Test Results' in body
                and '🤖 Generated by performance-report workflow' in body
                and not MULTIPART_COMMENT_PATTERN.search(body)):
            return comment

    return None


def _details_depth_delta(line: str) -> int:
    """Return net change in <details> nesting depth for a single line."""
    delta = len(DETAILS_OPEN_PATTERN.findall(line)) - len(DETAILS_CLOSE_PATTERN.findall(line))
    return delta


def _extract_top_level_details_blocks(text: str) -> list[str]:
    """Extract sibling <details> blocks, handling nested workload sections inside each."""
    blocks = []
    lines = text.split('\n')
    i = 0
    while i < len(lines):
        if lines[i].startswith('<details>'):
            block_lines = []
            depth = 0
            while i < len(lines):
                line = lines[i]
                block_lines.append(line)
                depth += _details_depth_delta(line)
                if depth == 0:
                    blocks.append('\n'.join(block_lines))
                    i += 1
                    break
                i += 1
        else:
            i += 1
    return blocks


def _strip_body_footer(comment_body: str) -> str:
    """Remove the workflow footer from a comment body."""
    if COMMENT_FOOTER in comment_body:
        return comment_body.split(COMMENT_FOOTER, 1)[0]
    return comment_body


def _find_previous_run_separator(content: str) -> str | None:
    """Return the previous-run section separator if present."""
    for separator in (PREVIOUS_RUN_SEPARATOR, LEGACY_PREVIOUS_RUNS_SEPARATOR):
        if separator in content:
            return separator
    return None


def extract_previous_runs(comment_body: str) -> list[str]:
    """Extract archived previous-run sections as a flat list of sibling blocks."""
    content = _strip_body_footer(comment_body)

    separator = _find_previous_run_separator(content)
    if separator:
        section = content.split(separator, 1)[1]
        return _extract_top_level_details_blocks(section)

    # Legacy comments used "Previous run (...)" summaries without the section header.
    previous_runs = []
    lines = content.split('\n')
    i = 0
    while i < len(lines):
        if lines[i].startswith('<details>'):
            lookahead = '\n'.join(lines[i:min(i + 5, len(lines))])
            if 'Previous run' not in lookahead:
                i += 1
                continue

            block_lines = []
            depth = 0
            while i < len(lines):
                line = lines[i]
                block_lines.append(line)
                depth += _details_depth_delta(line)
                if depth == 0:
                    previous_runs.append('\n'.join(block_lines))
                    i += 1
                    break
                i += 1
        else:
            i += 1

    return previous_runs


def extract_current_run_content(comment_body: str) -> str:
    """Extract the current run content, excluding archived previous runs and footer."""
    content = _strip_body_footer(comment_body)

    separator = _find_previous_run_separator(content)
    if separator:
        return content.split(separator, 1)[0].rstrip()

    # Legacy comments: drop archived "Previous run (...)" blocks at the end.
    lines = content.split('\n')
    result = []
    i = 0
    while i < len(lines):
        if lines[i].startswith('<details>'):
            lookahead = '\n'.join(lines[i:min(i + 5, len(lines))])
            if 'Previous run' in lookahead:
                break

        result.append(lines[i])
        i += 1

    return '\n'.join(result).rstrip()


def _format_previous_run_timestamp(dt: datetime) -> str:
    """Format a timestamp for previous-run collapsible labels (UTC)."""
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    else:
        dt = dt.astimezone(timezone.utc)
    return dt.strftime(PREVIOUS_RUN_TIMESTAMP_FORMAT)


def _previous_run_timestamp_from_comment(comment: dict) -> str:
    """Label for archiving a comment's current content as a previous run.

    Prefer created_at, then updated_at. Never invent "now" on parse failure —
    that would mis-date the archived run.
    """
    for field in ('created_at', 'updated_at'):
        raw = comment.get(field)
        if raw is None:
            continue
        if not isinstance(raw, str):
            print(
                f"Warning: comment {field} is not a string ({raw!r}); skipping",
                file=sys.stderr,
            )
            continue
        try:
            parsed = datetime.fromisoformat(raw.replace('Z', '+00:00'))
        except (ValueError, TypeError) as exc:
            print(
                f"Warning: failed to parse comment {field}={raw!r}: {exc}",
                file=sys.stderr,
            )
            continue
        return _format_previous_run_timestamp(parsed)

    print(
        "Warning: no usable created_at/updated_at on existing comment; "
        "labeling archived run without a concrete timestamp",
        file=sys.stderr,
    )
    return "Previous run"


def create_previous_run_section(content: str, run_timestamp: str) -> str:
    """Create a collapsible previous run section."""
    section = f"<details>\n<summary><strong>{run_timestamp}</strong></summary>\n\n"
    section += content
    section += "\n</details>\n\n"
    return section


def _trim_text(text: str, max_len: int) -> str | None:
    """Trim text to max_len, appending a truncation marker when shortened."""
    if len(text) <= max_len:
        return text
    marker = "\n\n...(truncated)...\n"
    if max_len <= len(marker):
        return None
    return text[:max_len - len(marker)] + marker


def _fit_previous_run_section(content: str, run_timestamp: str, max_len: int) -> str | None:
    """Build a previous-run section that fits within max_len, trimming content if needed."""
    wrapper = (
        f"<details>\n<summary><strong>{run_timestamp}</strong></summary>\n\n"
        "\n</details>\n\n"
    )
    if max_len <= len(wrapper):
        return None

    trimmed_content = _trim_text(content, max_len - len(wrapper))
    if trimmed_content is None:
        return None
    return create_previous_run_section(trimmed_content, run_timestamp)


def build_updated_comment_body(current_chunk: str, old_content: str,
                               old_timestamp: str) -> tuple[str | None, bool]:
    """
    Assemble an updated comment body within GitHub's size limit.

    Returns:
        (body, can_update) where can_update is False if the base report alone
        exceeds the limit and the caller should post a fresh comment instead.
    """
    base = current_chunk.replace(COMMENT_FOOTER, "").rstrip()
    min_body = base + COMMENT_FOOTER
    if len(min_body) > MAX_COMMENT_SIZE:
        return None, False

    extras = []
    remaining = MAX_COMMENT_SIZE - len(min_body)

    latest_section = create_previous_run_section(old_content, old_timestamp)
    latest_block = PREVIOUS_RUN_SEPARATOR + latest_section
    if len(latest_block) <= remaining:
        extras.append(latest_block)
    else:
        separator_budget = len(PREVIOUS_RUN_SEPARATOR)
        if remaining > separator_budget:
            fitted = _fit_previous_run_section(
                old_content, old_timestamp, remaining - separator_budget
            )
            if fitted:
                extras.append(PREVIOUS_RUN_SEPARATOR + fitted)

    body = base + ''.join(extras) + COMMENT_FOOTER
    if len(body) > MAX_COMMENT_SIZE:
        return None, False
    return body, True


def update_comment(owner: str, repo: str, comment_id: int, body: str, token: str) -> bool:
    """Update an existing comment."""
    url = f"https://api.github.com/repos/{owner}/{repo}/issues/comments/{comment_id}"
    headers = {
        'Authorization': f'token {token}',
        'Accept': 'application/vnd.github.v3+json'
    }

    data = {'body': body}

    response = requests.patch(url, headers=headers, json=data, timeout=30)

    if response.status_code == 200:
        return True
    else:
        print(f"Failed to update comment: {response.status_code} {response.text}", file=sys.stderr)
        return False


def post_comment(owner: str, repo: str, pr_number: int, body: str, token: str) -> bool:
    """Post a comment to a PR."""
    url = f"https://api.github.com/repos/{owner}/{repo}/issues/{pr_number}/comments"
    headers = {
        'Authorization': f'token {token}',
        'Accept': 'application/vnd.github.v3+json'
    }

    data = {'body': body}

    response = requests.post(url, headers=headers, json=data, timeout=30)

    if response.status_code == 201:
        return True
    else:
        print(f"Failed to post comment: {response.status_code} {response.text}", file=sys.stderr)
        return False


def main():
    parser = argparse.ArgumentParser(description='Post performance reports to GitHub PRs')
    parser.add_argument('--pr', type=int, action='append', dest='prs',
                        help='PR number(s) to comment on (can specify multiple)')
    parser.add_argument('--reports-dir', type=Path, required=True,
                        help='Directory containing workload report subdirectories')
    parser.add_argument('--run-id', required=True, help='Workflow run ID')
    parser.add_argument('--run-url', required=True, help='Workflow run URL')
    parser.add_argument('--status', required=True, choices=['success', 'failure'],
                        help='Workflow conclusion status')
    parser.add_argument('--baseline-id', help='Baseline run ID')
    parser.add_argument('--baseline-url', help='Baseline run URL')
    parser.add_argument('--owner', help='Repository owner (default: from GITHUB_REPOSITORY)')
    parser.add_argument('--repo', help='Repository name (default: from GITHUB_REPOSITORY)')

    args = parser.parse_args()

    if not args.prs:
        print("No PRs specified, nothing to do", file=sys.stderr)
        return 0

    # Get repo info
    if args.owner and args.repo:
        owner, repo = args.owner, args.repo
    else:
        owner, repo = get_repo_info()

    token = get_github_token()

    # Find all reports
    reports = find_reports(args.reports_dir)

    # Create comment chunks
    comment_chunks = create_comment_chunks(
        reports,
        args.run_id,
        args.run_url,
        args.status,
        args.baseline_id,
        args.baseline_url
    )

    print(f"Generated {len(comment_chunks)} comment chunk(s)", file=sys.stderr)

    # Post or update chunks for each PR
    success_count = 0
    total_posts = len(args.prs) * len(comment_chunks)

    for pr_number in args.prs:
        # For multi-chunk comments, we'll post new comments
        # For single chunk, we'll try to update existing comment
        if len(comment_chunks) == 1:
            # Try to find and update existing comment
            existing_comment = find_existing_comment(owner, repo, pr_number, token)

            if existing_comment:
                print(f"Found existing comment {existing_comment['id']} on PR #{pr_number}, updating...", file=sys.stderr)

                # Extract current run content (without footer and previous runs)
                old_content = extract_current_run_content(existing_comment['body'])

                # Timestamp from the existing comment (created_at, else updated_at)
                old_timestamp = _previous_run_timestamp_from_comment(existing_comment)

                # Extract any existing previous runs
                new_body, can_update = build_updated_comment_body(
                    comment_chunks[0], old_content, old_timestamp
                )

                if can_update and new_body:
                    if update_comment(owner, repo, existing_comment['id'], new_body, token):
                        success_count += 1
                        print("  ✓ Updated successfully", file=sys.stderr)
                    else:
                        print("  ✗ Failed to update", file=sys.stderr)
                else:
                    print(
                        f"Updated body exceeds comment size limit on PR #{pr_number}, "
                        "posting fresh comment...",
                        file=sys.stderr,
                    )
                    if post_comment(owner, repo, pr_number, comment_chunks[0], token):
                        success_count += 1
                        print("  ✓ Posted successfully", file=sys.stderr)
                    else:
                        print("  ✗ Failed to post", file=sys.stderr)
            else:
                # No existing comment, post new one
                print(f"No existing comment found on PR #{pr_number}, posting new comment...", file=sys.stderr)
                if post_comment(owner, repo, pr_number, comment_chunks[0], token):
                    success_count += 1
                    print("  ✓ Posted successfully", file=sys.stderr)
                else:
                    print("  ✗ Failed to post", file=sys.stderr)
        else:
            # Multiple chunks - post as new comments (too complex to update)
            for i, chunk in enumerate(comment_chunks):
                print(f"Posting part {i + 1}/{len(comment_chunks)} to PR #{pr_number}...", file=sys.stderr)

                if post_comment(owner, repo, pr_number, chunk, token):
                    success_count += 1
                    print("  ✓ Posted successfully", file=sys.stderr)
                else:
                    print("  ✗ Failed to post", file=sys.stderr)

    print(f"\nPosted/updated {success_count}/{total_posts} comment(s) successfully", file=sys.stderr)

    return 0 if success_count == total_posts else 1


if __name__ == '__main__':
    sys.exit(main())
