kind: Service
apiVersion: v1
metadata:
  name: webserver-{{.Replica}}-{{.Iteration}}
spec:
  selector:
    name: webserver-{{.Replica}}-{{.Iteration}}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
