---
apiVersion: v1
kind: Pod
metadata:
  name: samplepod
  annotations:
    kubernetes.v1.cni.cncf.io/networks: macvlan-conf
spec:
  containers:
  - name: samplepod
    command: ["/bin/bash", "-c", "sleep 2000000000000"]
    image: dougbtv/centos-network
    ports:
    - containerPort: 80