name: Docker-build
on: [pull_request]
jobs:
  build:
    name: Docker build
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
      GO111MODULE: on
      REPOSITORY: nfvpe/multus
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
  
      - name: Build latest-amd64
        run: docker build -t ${REPOSITORY}:latest-amd64 -f deployments/Dockerfile .
  
      - name: Build latest-ppc64le
        run: docker build -t ${REPOSITORY}:latest-ppc64le -f deployments/Dockerfile.ppc64le .
  
      - name: Build latest-origin
        run: docker build -t ${REPOSITORY}:latest-origin -f deployments/Dockerfile.openshift .
